# Lab Culture

The culture of the Health Policy Data Science Lab is inquisitive, collaborative, kind, and inclusive so that scholars can do their best work. Our group has high standards for rigor, quality, and ethics and helps each other learn to reach these objectives. Every team member is a human first, and their career goals will be centered and supported.  We are committed to an environment that is free from discrimination and harassment.

## Mutual Respect in the Lab

We strive for a culture of mutual respect in all of our communications, meetings, and policies. Please demonstrate respect for all Lab members by, for example, practicing active listening, speaking only for yourself and not others, and not dominating conversations. Mutual respect for each other's time includes being prepared (including drafting agendas), planning ahead, and starting/ending meetings at the scheduled time.

## Respect for the People Represented in Study Data

A key value in the Lab is deep respect for the people and communities whose information is represented in the data we study. We engage seriously in learning about the policies, institutional structures, societal biases, and lived experiences that underlie these data sources.

This respect also involves careful attention to data privacy and protection, discussed in @sec-data.

## Working Hours {#sec-working-hours}

Lab members are encouraged to work efficiently and effectively on a schedule that works well for them. **We do not support a culture of overwork!** 

Dr. Rose does not expect you to be working in the evenings or on weekends and asks that you respect Lab members' evening and weekend time as well. This includes not expecting Dr. Rose to review your work product, submit letters, or otherwise be available for typical work tasks outside business hours.

We embrace time off, breaks from meetings, and vacations!

## Trainee Support, Access, and Accomodations

Your physical and mental health are incredibly important. Please familiarize yourself with the [mental health](https://studentaffairs.stanford.edu/mental-health-resources-stanford) and [crisis assistance](https://glo.stanford.edu/glo-services/crisis-assistance) resources available for students at Stanford as well as mental [health resources](https://postdocbenefits.stanford.edu/my-benefits/medical-coverage/mental-health-resources) for postdoctoral scholars.

Stanford is committed to providing equal educational opportunities for disabled students. Disabled students are a valued and essential part of the Stanford community. If you experience disability, please register with the [Office of Accessible Education (OAE)](https://oae.stanford.edu/). Professional staff at OAE will evaluate your needs, support appropriate and reasonable accommodations, and prepare an Academic Accommodation Letter for faculty. If you already have an Academic Accommodation Letter, Stanford invites you to share your letter with your advisor. Academic Accommodation Letters should be shared at the earliest possible opportunity so we may partner with you and OAE to identify any barriers to access and inclusion that might be encountered in your experience.
