# General Policies

It is important that each trainee and Dr. Rose have a shared understanding of expectations regarding research in the Lab and academic progress in the trainee's degree or postdoctoral program. The policies in this chapter aim to aid in this goal.

## Joining the Lab

Dr. Rose keeps a page updated [on her website](http://drsherrirose.org/new-students-and-postdocs) regarding whether she is taking new students, hiring postdocs, or available for dissertation committees. At Stanford, we've had students from many different graduate programs join the Lab, including health policy, biomedical data science, computer science, and chemical engineering programs. 

## Recurring Meetings

Lab trainees meet individually with Dr. Rose regularly. This is typically weekly or every other week depending on the needs of the trainee and their projects. Meetings are either 25 minutes or 50 minutes to allow for breaks between meetings. Dr. Rose expects trainees to manage the meeting such that it ends on time.

In general, Dr. Rose expects progress to be made between each meeting. Progress can include struggling with the material. Dr. Rose cares that you are engaged and taking initiative to advance the project. We’ll discuss what you learned and where you are still confused. When we identify areas where you have gaps, Dr. Rose does expect you to invest in learning the required material and to follow through to fill those gaps. All trainees must be making satisfactory academic progress in line with the expectations of their graduate degree program.

If you do not need to meet a particular week (e.g., making steady progress and don't have questions), please email Dr. Rose in advance so she can efficiently reallocate the meeting time. Your physical and mental health are important. If you need to cancel a meeting for health or personal reasons, email Dr. Rose. As much notice as is possible is helpful, but it is always better to cancel a meeting short notice than to attend when you are sick!

If there are repeated meeting cancellations, we should discuss the underlying reasons.

Please also see @sec-meeting-agendas for details on recurring meeting agendas and GitHub repository updates.

## Meeting Agendas & GitHub Repository Updates {#sec-meeting-agendas}

Trainees must prepare an agenda prior to each recurring meeting with Dr. Rose. Create a google doc (invite Dr. Rose as editor) that you’ll add to in reverse chronological order for each meeting with the information below included. Update the google doc by 11AM *one business day* before our meeting. Push a commit to the project's GitHub repository at the same time, even if you plan to make further changes prior to the meeting. If additional changes are made to the repository ahead of the meeting, push a second commit. Repeatedly not creating agendas will result in cancelled meetings.

**[Meeting Date]**

- What has been completed since previous meeting:
- Topics to discuss at the meeting:
- What will be completed by the next meeting:

## Individual Development Plans 

If Dr. Rose is your primary advisor, students and postdoctoral scholars should complete the Stanford Individual Development Plan (IDP) when joining the Lab and then annually thereafter ([student forms](https://oge.stanford.edu/academics/idp/forms/), [initial form for postdocs](https://postdocs.stanford.edu/sites/default/files/opa_idp-initial_0.pdf), [annual form for postdocs](https://postdocs.stanford.edu/sites/default/files/opa_idp-annual_0.pdf)). This applies regardless of home department. Trainees should plan to check in on progress made toward IDP goals once a quarter. Dr. Rose expects that trainees will be responsible for scheduling the annual IDP meetings and adding the IDP check-ins once a quarter to the agenda for an existing recurring meeting.

## Academic Progress in Graduate Degree Programs

If you are a graduate student and Dr. Rose is your primary advisor, please create and regularly update a shared document that includes major degree requirements (e.g., coursework, teaching, qualifying exams, etc) and completion status (e.g., completed, planned completion date). Include links at the top to the graduate degree handbook from your home department as well as key contacts in your home department who should be kept apprised of your academic progress. This document will be discussed quarterly along with the IDP check-ins, and students should add it to the agenda for an existing recurring meeting.

## Registering for Units

Graduate students should discuss their plans to register for research units with Dr. Rose each term (often BIOMEDIN 299 or HRP 399). Units should be taken credit/no credit and not for a letter grade. Permission codes are currently required to register for research units. 

## Deadlines

We aim to set ambitious yet feasible target deadlines for work product in a collaborative process. It is often the case that research takes longer than we expect, and an internal agreed-upon deadline is no longer possible. If you anticipate missing a deadline, contact Dr. Rose. It is an expectation in the Lab that all members are proactive about discussing revised deadlines rather than waiting until after the deadline has passed. If a trainee is repeatedly missing deadlines, we should discuss the underlying reasons.

## Lab Meetings & Events

The Lab holds Lab Meetings and various types of events throughout the year, including lunches, data jamborees, coffee chats, and journal clubs. If you have ideas for events, suggestions are always welcome.

Food at Lab events is funded by the Lab and free to Lab attendees. We expect that trainees who RSVP and submit food orders will show up to the event, barring illness or personal situation. If you need to change your RSVP, please contact Dr. Rose to help us avoid food waste.

## Recommendation Letters

Dr. Rose receives a variety of requests for letters from current and former trainees, including for graduate school, job applications, fellowships, and awards. Please know she treats your letter requests with the seriousness they deserve and recognizes their importance. Dr. Rose asks that you respect the time it takes her to write, revise, and send letters by giving plenty of notice and being organized with your requests.

It essential that you ask Dr. Rose if she can write you a recommendation letter before submitting her name as a recommender. It may be the case that a letter from someone else will be more beneficial for you or that the deadline is too soon for her to accommodate your request. 

In general, please give Dr. Rose at least 4 weeks notice when requesting a letter, and more time than that when possible. If the deadline is sooner than 4 weeks, she may not be able to write the letter, particularly during times of the year when she receives a high volume of letter requests. 

## Communication

We have a Lab **slack**. Lab members can search for "HPDS Lab" in the [Workspaces at Stanford](https://stanford.enterprise.slack.com/) and request to join.

Please keep in mind our Lab philosophy on working hours in @sec-working-hours. Do not assume that because you have sent a slack message or email that you should get an instant reply.

