# Computing Resources

## Nero GCP

Stanford's [Nero Google Cloud Platform (GCP)](https://nero-docs.stanford.edu/gcp-overview.html) is the environment often most suitable or required for the analysis of data sources discussed in @sec-data. There are costs associated with Nero GCP and we must keep careful track of these. 

If you have questions about which environment you should use for your data analyses, please ask so we can be certain to follow all data security and privacy requirements.

## Sherlock

Stanford has a High Performance Computing cluster called [Sherlock](https://www.sherlock.stanford.edu/docs/). See this information on [getting started](https://www.sherlock.stanford.edu/docs/getting-started/), [connecting](https://www.sherlock.stanford.edu/docs/getting-started/connecting/), and [submitting jobs](https://www.sherlock.stanford.edu/docs/getting-started/submitting/). The Lab has a dedicated node on Sherlock. 

Sherlock is most frequently used for analyses involving simulated data as it is [not designed for data with a high risk classification](https://www.sherlock.stanford.edu/docs/concepts/#data-risk-classification). If you have questions about which environment you should use for your data analyses, please ask so we can be certain to follow all data security and privacy requirements.

## Software

Much of the software we use in the Lab is available open source for free. Please let Dr. Rose know if there is non-free software that would be helpful for your research and we can likely purchase this with research funds.

#### Statistical Computing {.unnumbered}

- R: [Download Free](https://cran.r-project.org/)
- RStudio: [Download Free](https://posit.co/products/open-source/rstudio/)
- Python: [Download Free](https://www.python.org/downloads/)

#### Illustration {.unnumbered}

- OmniGraffle: [Purchase Subscription or One-Time Download](https://store.omnigroup.com/omnigraffle)
- Adobe Illustrator: [Free via Stanford Branner Earth Science Library](https://library.stanford.edu/branner/using-branner-library) or [Purchase Adobe Creative Cloud License](https://web.stanford.edu/dept/its/cgi-bin/services/software/portal/detail.php?action=view_product&product_id=1163) 
