# Conferences

Conferences provide an opportunity to learn about new research, get feedback on your own research, practice presentation skills, take a short course, network, and more. Dr. Rose is happy to discuss conferences relevant to your research and career goals in our meetings.

If we have discussed a conference and Dr. Rose is funding your trip, please send Dr. Rose a projected budget for the trip *before* purchasing plane tickets, registrations, or reserving hotels.

Lab members can view our internal list of upcoming conference presentations [here](https://github.com/StanfordHPDS/conferences).

## Stanford Travel Policies

Flights for Lab trainees and staff **must** be purchased through Stanford Travel. They are not reimbursable otherwise. Hotels **must** be purchased through Stanford Travel unless it is a conference hotel. Please copy Dr. Rose on travel-related emails with administrative staff.

**Health Policy and Biomedical Data Science Students**: If you are presenting at a conference, submit for up to $1,000 of those expenses to be reimbursed through the [Biosciences Travel Grant Program](https://oge.stanford.edu/financial/travel-grant-program/). You are eligible for one conference per year.

## Slides

We have an experimental lab slide template for Quarto located in our [GitHub repository](https://github.com/StanfordHPDS/hpds-slides-theme). This template uses [reveal.js](https://quarto.org/docs/presentations/revealjs.html). This slide template is not required for lab presentations, but it may be a useful starting point.

There are several good resources for creating effective scientific presentations. Here are a couple:

- [Better Presentations](https://cup.columbia.edu/book/better-presentations/9780231175210/) by Jonathan Schwabish
- [The Motivated Speaker](https://www.articulationinc.com/the-motivated-speaker-book/) by Ruth Milligan, Acacia Duncan, and Blythe Coons

One issue to consider when presenting results from a paper is whether to use the same figures and tables as in the paper or create new ones. Often, the details in a paper figure or table may not be necessary for a presentation. Consider simplifying figures and tables to focus on the key message you want to convey. See the ["Telling a story and making a point" chapter of Fundamentals of Data Visualization](https://clauswilke.com/dataviz/telling-a-story.html) for more guidance.

Lab meetings are also good opportunity to practice your presentation skills and get feedback from lab members.

## Posters

We have an experimental lab poster template for Quarto located in our [GitHub repository](https://github.com/StanfordHPDS/hpds-poster). This template uses [Typst](https://quarto.org/docs/output-formats/typst.html). This poster template is not required, but it may be a useful starting point.

A poster printing service local to Stanford is [Biotech Productions](https://www.biotech-productions.com/), which lab members have used in the past with good experiences.

## Conferences by Field {#sec-conferences-field}

We include below a noncomprehensive list of conferences that may be of interest to Lab members.

#### Algorithmic Bias & Fairness {.unnumbered}

- [ACM FAccT](https://facctconference.org)
- [AAI/ACM AI, Ethics, & Society](https://www.aies-conference.com/)
- [ACM EAAMO](https://eaamo.org/)
- [IEEE SaTML](https://satml.org/)

#### Machine Learning for Health {.unnumbered}

- [Machine Learning for Health Care](https://www.mlforhc.org/)
- [CHIL](https://www.chilconference.org/)
- [Machine Learning for Health](https://ml4health.github.io/)

#### Statistics {.unnumbered}

- [International Conference on Health Policy Statistics](https://ww2.amstat.org/meetings/ichps/2025/)
- [ENAR](https://www.enar.org/meetings/future.cfm)
- [Joint Statistical Meetings](https://www.amstat.org/asa/meetings/Joint-Statistical-Meetings.aspx)

#### Epidemiology {.unnumbered}

- [Society for Epidemiologic Research](https://epiresearch.org/annual-meeting/)

#### Health Economics {.unnumbered}

- [ASHEcon](https://www.ashecon.org/conferences/)
- [iHEA](https://healtheconomics.org/)
- [Economics of AI](https://www.economicsofai.com/nber-conference-toronto-2023)

#### Health Policy {.unnumbered}

- [AcademyHealth](https://academyhealth.org/events/2023-06/2023-annual-research-meeting)
- [ISPOR](https://www.ispor.org/conferences-education/conferences)

#### Decision Science {.unnumbered}

- [SMDM](https://smdm.org/meetings)

#### Statistical Programming {.unnumbered}

- [posit::conf()](https://posit.co/conference/)
- [SciPy](https://www.scipy2024.scipy.org/)
- [useR!](https://user2024.r-project.org/)
- [PyCon](https://us.pycon.org/2024/)
- [New York R Conference](https://rstats.ai/nyr)
