# Publications

## Authorship

We aim to discuss authorship early in the research process and have continuing conversations regarding team member roles. Plans can change and contributions may evolve over time. If you have authorship questions during the process of working on a project, we want you to feel empowered to ask these questions!

**It is an expectation in the Lab that no new authors are invited to join an existing Lab project (i.e., where Dr. Rose is the lead PI) without the prior agreement of, at a minimum, Dr. Rose and the first author(s).**

The Lab follows the [ICMJE recommendations](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) regarding who is included as an author.

What does first authorship mean in our Lab? Being the first author typically means that you are: (1) an intellectual lead on the project, (2) making major contributions conducting the scientific work (e.g., developing methodology, analyzing data), and (3) a main writer on the manuscript, usually crafting the first draft. For some projects, a first authorship role may also involve project management with collaborators and partners. All of these activities are done under the mentorship of Dr. Rose as the PI with substantial feedback in an apprenticeship model.

### Does Code Review Merit Authorship?

Code review is an important part of the scientific process, and we require Lab members to have their code reviewed (@sec-code-review). However, code review alone does not necessarily merit authorship. Authorship requires substantial contributions to the scientific work, as described above. That said, code review can organically lead to deeper involvement in the project that may merit authorship.

## Acknowledgments

Grants that fund research in the Lab must be recognized in our manuscripts, typically in the Acknowledgments section. If you have questions about which grant funded our work, ask Dr. Rose. See @sec-active-funding for grant information, including grant numbers.

## Preprints

We typically post preprints on [arXiv](https://arxiv.org/), [medRxiv](https://www.medrxiv.org/), or as an [NBER](https://www.nber.org/) Working Paper.

## On Least Publishable Units

We aim to write papers with an appropriate scope suitable for the goals of the project. We do not focus on [salami slicing](https://academic.oup.com/ije/article/49/1/281/5570871) or least publishable unit papers. This is not to confuse least publishable units with short, rigorous papers. Short papers can be good and high quality with strong standards.

## Types of Papers

The structure and content of a manuscript varies by discipline and audience.

Example Lab publications by journal type: [statistics](https://onlinelibrary.wiley.com/doi/10.1111/biom.13863), [medical](https://jamanetwork.com/journals/jamapsychiatry/fullarticle/2765490?guestAccessKey=8e0d777c-ac53-47e9-9387-722b788058a2&utm_campaign=author_alert-jamanetwork&utm_content=author-author_engagement&utm_medium=email&utm_source=jps&utm_term=1m), [health policy](https://www.healthaffairs.org/doi/full/10.1377/hlthaff.2015.1026), [health services research](https://onlinelibrary.wiley.com/doi/10.1111/1475-6773.13046), [health economics](https://www.journals.uchicago.edu/doi/10.1086/716199), [epidemiology](https://academic.oup.com/aje/article/185/1/65/2662306), [computer science conference paper](https://proceedings.mlr.press/v180/chapfuwa22a.html).

## Journals

The journal lists below are not exhaustive and largely focus on outlets where Lab members have previously published their work. Decisions about where to submit manuscripts for publication are made collaboratively to balance the needs and priorities of the team with as much deference as possible to what is best for the trainee author(s). We also publish in peer-reviewed conference proceedings, see @sec-conferences-field.

Lab members can view our internal list of upcoming and recent publications [here](https://github.com/StanfordHPDS/publications).

#### Health Economics & Policy {.unnumbered}

[Journal of Health Economics](https://www.journals.elsevier.com/journal-of-health-economics), [American Journal of Health Economics](https://www.journals.uchicago.edu/toc/ajhe/current), [Health Affairs](https://www.healthaffairs.org/), [Health Services Research](https://www.hsr.org/), [Medical Care](https://journals.lww.com/lww-medicalcare/pages/default.aspx), [Medical Decision Making](https://journals.sagepub.com/home/mdm),  [JAMA Health Forum](https://jamanetwork.com/journals/jama-health-forum)

#### Epidemiology & Public Health {.unnumbered}

[American Journal of Epidemiology](https://academic.oup.com/aje), [Epidemiology](https://journals.lww.com/epidem/pages/default.aspx), [International Journal of Epidemiology](https://academic.oup.com/ije), [American Journal of Public Health](https://ajph.aphapublications.org/)

#### Statistics {.unnumbered}

[Journal of the American Statistical Association](https://www.tandfonline.com/toc/uasa20/current), [Biometrics](https://onlinelibrary.wiley.com/journal/15410420), [Biostatistics](https://academic.oup.com/biostatistics) (_COI: Sherri was Co-Editor-in-Chief_), [Statistics in Medicine](https://onlinelibrary.wiley.com/journal/10970258), [Statistical Methods in Medical Research](https://journals.sagepub.com/home/smm)

#### Clinical {.unnumbered}

[NEJM](https://www.nejm.org/), [JAMA](https://jamanetwork.com/), [JAMA Internal Medicine](https://jamanetwork.com/journals/jamainternalmedicine), [JAMA Psychiatry](https://jamanetwork.com/journals/jamapsychiatry)

#### Health Informatics & Digital Health {.unnumbered}

[JAMIA](https://academic.oup.com/jamia), [BMJ Health & Care Informatics](https://informatics.bmj.com/), [Lancet Digital Health](https://www.thelancet.com/journals/landig/home)
