# Pre-Flight Checklist for Publications {#sec-checklist}

## Crosscheck

As discussed in @sec-code-review and @sec-agreements, your analysis should be regularly checked for correctness and adherence to Lab agreements, *not* just at the end of the project. However, it's useful to have a final check (by you and at least one other person) before submitting for publication. Regular code review will make this final check quicker and easier, so please do both.

Note: For pre-prints, run through this checklist for both uploading to the pre-print server as well as for when you formally submit the project to a journal.

## Pre-Flight Checklist

### Repository and Files

- [ ] Confirm again that no sensitive data is included in the repository. Check files, Jupyter caches, etc.
- [ ] There is a `README` file (any of: `README.md`, `README.Rmd`, `README.qmd`).
- [ ] `README` contains clear instructions on how to run the code. See @sec-readme for details.
- [ ] Create a new public repository for the project and archive the private repository.

### Code and Reproducibility

- [ ] The code follows the team style guide. See @sec-code-style for details.
- [ ] Query code from user interfaces, e.g., Redivis or BigQuery, are up to date in version control.
- [ ] For any random processes such as simulation, a seed is set for reproducibility.
- [ ] The code uses a package environment to lock packages. See @sec-pkg-env for details.
- [ ] Manuscript is generatable via Quarto. See @sec-quarto for details.
- [ ] Run the code one last time in a fresh environment, preferably on a different computer. See @sec-running-code for details.

### Submission

- [ ] Follow Data Use Agreement requirements regarding project review from a third party prior to submission.
- [ ] Check if journal has specific code and reproducibility guidelines.
- [ ] Check figures and tables for correctness.
- [ ] Check <https://www.zotero.org/styles> for a citation style file for the journal of interest. Include the file in your Quarto metadata and in the repository.
- [ ] For sensitive data, confirm small cell definition for the project. Check that no small cells are included in tables or figures.  See for @sec-data for details.
- [ ] Use a GitHub release for the submission version. See @sec-gh-release for details.
- [ ] If there are any research outputs other than a manuscript, such as a (simulated/synthetic) data, register them for a DOI at a service like OSF or Zenodo.

### Acceptance

- [ ] If the project exists as a pre-print, update the pre-print page to include information about the peer-reviewed publication.

### Opt-in Workflows (@sec-opt-in)

- [ ] Opt-in: Pipeline code is documented and with clear instructions for running the pipeline. See @sec-pipelines for details.
- [ ] Opt-in: If code contains tests, tests pass. See @sec-tests for details.
- [ ] Opt-in: Dockerfile is included in repository with clear instructions for running the image. See @sec-docker for details.
